name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        python -m pytest -v --cov=app --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push to Azure Container Registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/chat-aug-back:${{ github.sha }}
    
    - name: Deploy to Azure Container Apps
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
        az containerapp update \
          --name chat-aug-back \
          --resource-group your-resource-group \
          --image ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/chat-aug-back:${{ github.sha }}
